package org.ning.leetcode.algorithms.easy._389_FindDifference;

/**
 * 389. Find the Difference <br/>
 * Given two strings s and t which consist of only lowercase letters. <br/>
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position. <br/>
 * Find the letter that was added in t. <br/>
 * Example:<br/>
 * Input: s = "abcd" t = "abcde" <br/>
 * Output: e <br/>
 * Explanation: 'e' is the letter that was added.
 */
public class Solution {
    public char findTheDifference(String s, String t) {
        char[] arr1 = s.toCharArray();
        char[] arr2 = t.toCharArray();

        char result = 0;
        for (int i = 0; i < arr1.length; i++) {
            result ^= arr1[i];
        }

        for (int i = 0; i < arr2.length; i++) {
            result ^= arr2[i];
        }

        return result;
    }
}
